# Yaml file for SubWorld_DP

# Parameters for chart generation
seed: 2525
dim: 152
n_islands: None
min_islands: 16
max_islands: 20
size: 10.0
min_height: 0.9
max_height: 2.0
x_decay_min: 1.5
x_decay_max: 3.0
y_decay_min: 1.5
y_decay_max: 3.0
max_cur: 0.5

# Parameters for value function generation
target_x: 49
target_y: 103
discount: 0.9
n_t: 5
n_h: 16
tol: -6

# Extra parameters for many chart/value generations
n_cpu: 48
maps_i: 0
maps_f: 150

# Parameters for GPS policy generation
sub_x: None
sub_y: None
n_steps: 25
gps_cost: 0.45
cur_cost: 0.01
uncert_pos: 0.2
uncert_cur: 0.2
