# Yaml file for SubWorld_DP

# Parameters for chart generation
seed: 25252531
dim: 152
n_islands: 20
max_islands: 20
size: 10.0
min_height: 0.9
max_height: 2.0
x_decay_min: 1.5
x_decay_max: 3.0
y_decay_min: 1.5
y_decay_max: 3.0
max_cur: 0.5

# Parameters for value function generation
target_x: 49
target_y: 103
discount: 0.9
n_t: 5
n_h: 16
tol: -6

# Extra parameters for many chart/value generations
n_cpu: 4
maps_i: 25252525
maps_f: 25252550

# Parameters for GPS policy generation
sub_x: None
sub_y: None
n_steps: 50
gps_cost: 0.0
cur_cost: 0.0
uncert_pos: 0.1
uncert_cur: 0.1
